### ISSUE TITLE
There a way of showing the MD5 signature from the STREAMINFO block using tagpy?

### ISSUE THREAD

**Issue by audiomuze** [hobophobe/tagpy#1]
As per the subject title, can one pull the md5 sig from FLAC files using tagpy?  If not, would you consider adding the capability?

**Comment by hobophobe** [comment]
It doesn't support that as of the last upstream version (which has apparently stopped work on it). I only ever made minor changes to get `tagpy` working on python3 some years ago, so I'm not sure how difficult improving FLAC support would be. `tagpy` wraps calls to `taglib`, which does support it as a `signature` according to [taglib.org: API: "TagLib::FLAC::Properties Class Reference"](https://taglib.org/api/classTagLib_1_1FLAC_1_1Properties.html), so it's possible.

That said, it looks like [pytaglib](https://github.com/supermihi/pytaglib) (which also wraps `taglib`) has more forks and possibly more support. Someone who works on that might add support there (as it also seems to lack it at present).

Digging around for other options that work with Python and support getting the signature, though they don't use `taglib`:

[Mutagen](https://github.com/quodlibet/mutagen/) supports getting it via `file.info.md5_signature`. I already had it installed so I was able to verify it works easily enough:

    >>> import mutagen
    >>> mu_file = mutagen.file("music.flac")
    >>> mu_file.info.md5_signature
    [md5 as base10 integer]

[Python Audio Tools](https://github.com/tuffy/python-audio-tools) also seems to support getting the md5. I didn't install it to try and don't know what getting to the md5 looks like codewise, but it does support it. Depending on your needs, either alternative might or might not be a good fit.

**Comment by audiomuze** [comment]
Thanks, I'm aware of mutagen and currently using it, but for speed I'm keen to transition to taglib.
